# Generated by Django 4.1.5 on 2023-01-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('startdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='jockey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('time', models.TimeField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.battle')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.horse')),
                ('jockey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.jockey')),
            ],
        ),
        migrations.AddField(
            model_name='horse',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.owner'),
        ),
    ]
