# Generated by Django 4.1.5 on 2023-01-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='sex',
            field=models.CharField(choices=[('male', 'Муж.'), ('female', 'Жен.')], default='1', max_length=10),
        ),
    ]
